### ISSUE TITLE
Comment some locales out.

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/locale-gen#1]
@MingcongBai is working on this.

**Comment by Artoria2e5** [comment]
Many months ago @MingcongBai told me that not generating some locales will fail per-locale font matching in browsers.

**Comment by Artoria2e5** [comment]
But it's really really bad to try to generate all the locales...

**Comment by Artoria2e5** [comment]
Bai, how about commenting out all non-UTF-8 locales first?

**Comment by MingcongBai** [comment]
Works for me... I will do it later tonight.

**Comment by Artoria2e5** [comment]
Legacy Encoding Exclusion Act implemented as AOSC-Dev/aosc-os-core@16049b4.

**Comment by Artoria2e5** [comment]
Hmm, will anyone run a `/usr/bin/time` for this?

**Comment by MingcongBai** [comment]
A todo for today or tomorrow (keeping the window open).

**Comment by MingcongBai** [comment]
Now in effect for Core 4.1. Closing.
